// Auto-generated by scripts/generate-api-tests.ts
// Do not edit manually - regenerate with: bun run scripts/generate-api-tests.ts

import '../../scripts/kit-sdk';

// =============================================================================
// Test Infrastructure
// =============================================================================

interface TestResult {
  test: string;
  status: 'running' | 'pass' | 'fail' | 'skip';
  timestamp: string;
  result?: unknown;
  error?: string;
  duration_ms?: number;
}

function logTest(name: string, status: TestResult['status'], extra?: Partial<TestResult>) {
  const result: TestResult = {
    test: name,
    status,
    timestamp: new Date().toISOString(),
    ...extra
  };
  console.log(JSON.stringify(result));
}

function debug(msg: string) {
  console.error(`[TEST] ${msg}`);
}

async function runTest(name: string, fn: () => Promise<void>) {
  logTest(name, 'running');
  const start = Date.now();
  try {
    await fn();
    logTest(name, 'pass', { duration_ms: Date.now() - start });
  } catch (err) {
    logTest(name, 'fail', { error: String(err), duration_ms: Date.now() - start });
  }
}

function skipTest(name: string, reason: string) {
  logTest(name, 'skip', { error: reason });
}

// =============================================================================
// Tests
// =============================================================================

debug('test-utility-apis.ts starting...');

// -----------------------------------------------------------------------------
// exec() tests
// -----------------------------------------------------------------------------

await runTest('exec-basic', async () => {
  const result = await exec('echo "hello"');
  if (!result || typeof result.stdout !== 'string') {
    throw new Error('Expected exec result with stdout');
  }
  debug(`exec stdout: ${result.stdout.trim()}`);
});

// -----------------------------------------------------------------------------
// HTTP tests (get, post, put, patch, del)
// -----------------------------------------------------------------------------

await runTest('get-request', async () => {
  const result = await get('https://jsonplaceholder.typicode.com/todos/1');
  if (!result || !result.data) {
    throw new Error('Expected response with data');
  }
  debug(`get result: ${JSON.stringify(result.data).slice(0, 100)}`);
});

await runTest('post-request', async () => {
  const result = await post('https://jsonplaceholder.typicode.com/posts', {
    title: 'Test',
    body: 'Test body',
    userId: 1,
  });
  if (!result || !result.data) {
    throw new Error('Expected response with data');
  }
});

await runTest('put-request', async () => {
  const result = await put('https://jsonplaceholder.typicode.com/posts/1', {
    id: 1,
    title: 'Updated',
    body: 'Updated body',
    userId: 1,
  });
  if (!result || !result.data) {
    throw new Error('Expected response with data');
  }
});

await runTest('patch-request', async () => {
  const result = await patch('https://jsonplaceholder.typicode.com/posts/1', {
    title: 'Patched',
  });
  if (!result || !result.data) {
    throw new Error('Expected response with data');
  }
});

await runTest('del-request', async () => {
  const result = await del('https://jsonplaceholder.typicode.com/posts/1');
  // DELETE typically returns empty or the deleted resource
  if (typeof result !== 'object') {
    throw new Error('Expected response object');
  }
});

// -----------------------------------------------------------------------------
// wait() tests
// -----------------------------------------------------------------------------

await runTest('wait-basic', async () => {
  const start = Date.now();
  await wait(100);
  const elapsed = Date.now() - start;
  if (elapsed < 90) {
    throw new Error(`wait() returned too quickly: ${elapsed}ms`);
  }
});

// -----------------------------------------------------------------------------
// Window control tests (fire-and-forget)
// -----------------------------------------------------------------------------

skipTest('show-window', 'Fire-and-forget - cannot verify');
skipTest('hide-window', 'Fire-and-forget - cannot verify');
skipTest('blur-window', 'Fire-and-forget - cannot verify');

debug('test-utility-apis.ts completed!');
