// Auto-generated by scripts/generate-api-tests.ts
// Do not edit manually - regenerate with: bun run scripts/generate-api-tests.ts

import '../../scripts/kit-sdk';

// =============================================================================
// Test Infrastructure
// =============================================================================

interface TestResult {
  test: string;
  status: 'running' | 'pass' | 'fail' | 'skip';
  timestamp: string;
  result?: unknown;
  error?: string;
  duration_ms?: number;
}

function logTest(name: string, status: TestResult['status'], extra?: Partial<TestResult>) {
  const result: TestResult = {
    test: name,
    status,
    timestamp: new Date().toISOString(),
    ...extra
  };
  console.log(JSON.stringify(result));
}

function debug(msg: string) {
  console.error(`[TEST] ${msg}`);
}

async function runTest(name: string, fn: () => Promise<void>) {
  logTest(name, 'running');
  const start = Date.now();
  try {
    await fn();
    logTest(name, 'pass', { duration_ms: Date.now() - start });
  } catch (err) {
    logTest(name, 'fail', { error: String(err), duration_ms: Date.now() - start });
  }
}

function skipTest(name: string, reason: string) {
  logTest(name, 'skip', { error: reason });
}

// =============================================================================
// Tests
// =============================================================================

debug('test-media-apis.ts starting...');

// -----------------------------------------------------------------------------
// term() tests
// -----------------------------------------------------------------------------

await runTest('term-with-command', async () => {
  const result = await term('echo "hello from term"');
  if (typeof result !== 'string') {
    throw new Error(`Expected string output, got ${typeof result}`);
  }
});

// -----------------------------------------------------------------------------
// chat() tests
// -----------------------------------------------------------------------------

await runTest('chat-basic', async () => {
  const result = await chat();
  if (typeof result !== 'string') {
    throw new Error(`Expected string, got ${typeof result}`);
  }
});

// -----------------------------------------------------------------------------
// widget() tests
// -----------------------------------------------------------------------------

await runTest('widget-basic', async () => {
  const w = await widget('<div class="p-4">Widget Test</div>', {
    width: 200,
    height: 100,
  });
  if (!w || typeof w.close !== 'function') {
    throw new Error('Expected widget controller with close method');
  }
  w.close();
});

// -----------------------------------------------------------------------------
// eyeDropper() tests
// -----------------------------------------------------------------------------

await runTest('eyeDropper-basic', async () => {
  const result = await eyeDropper();
  if (!result || typeof result.sRGBHex !== 'string') {
    throw new Error('Expected color info with sRGBHex property');
  }
});

// -----------------------------------------------------------------------------
// find() tests
// -----------------------------------------------------------------------------

await runTest('find-basic', async () => {
  const result = await find('Search for files');
  if (typeof result !== 'string') {
    throw new Error(`Expected string path, got ${typeof result}`);
  }
});

// -----------------------------------------------------------------------------
// Hardware-dependent tests (skipped)
// -----------------------------------------------------------------------------

skipTest('webcam-capture', 'Requires camera hardware');
skipTest('mic-capture', 'Requires microphone hardware');

debug('test-media-apis.ts completed!');
