// Auto-generated by scripts/generate-api-tests.ts
// Do not edit manually - regenerate with: bun run scripts/generate-api-tests.ts

import '../../scripts/kit-sdk';

// =============================================================================
// Test Infrastructure
// =============================================================================

interface TestResult {
  test: string;
  status: 'running' | 'pass' | 'fail' | 'skip';
  timestamp: string;
  result?: unknown;
  error?: string;
  duration_ms?: number;
}

function logTest(name: string, status: TestResult['status'], extra?: Partial<TestResult>) {
  const result: TestResult = {
    test: name,
    status,
    timestamp: new Date().toISOString(),
    ...extra
  };
  console.log(JSON.stringify(result));
}

function debug(msg: string) {
  console.error(`[TEST] ${msg}`);
}

async function runTest(name: string, fn: () => Promise<void>) {
  logTest(name, 'running');
  const start = Date.now();
  try {
    await fn();
    logTest(name, 'pass', { duration_ms: Date.now() - start });
  } catch (err) {
    logTest(name, 'fail', { error: String(err), duration_ms: Date.now() - start });
  }
}

function skipTest(name: string, reason: string) {
  logTest(name, 'skip', { error: reason });
}

// =============================================================================
// Tests
// =============================================================================

debug('test-file-apis.ts starting...');

// -----------------------------------------------------------------------------
// hotkey() tests
// -----------------------------------------------------------------------------

await runTest('hotkey-capture', async () => {
  const result = await hotkey('Press a key');
  if (!result || typeof result.key !== 'string') {
    throw new Error('Expected hotkey info with key property');
  }
  debug(`hotkey captured: ${result.key}`);
});

// -----------------------------------------------------------------------------
// drop() tests
// -----------------------------------------------------------------------------

await runTest('drop-basic', async () => {
  const result = await drop();
  if (!Array.isArray(result)) {
    throw new Error(`Expected array, got ${typeof result}`);
  }
});

// -----------------------------------------------------------------------------
// path() tests
// -----------------------------------------------------------------------------

await runTest('path-basic', async () => {
  const result = await path({ startPath: '/tmp', hint: 'Select a file' });
  if (typeof result !== 'string') {
    throw new Error(`Expected string path, got ${typeof result}`);
  }
});

debug('test-file-apis.ts completed!');
