// Auto-generated by scripts/generate-api-tests.ts
// Do not edit manually - regenerate with: bun run scripts/generate-api-tests.ts

import '../../scripts/kit-sdk';

// =============================================================================
// Test Infrastructure
// =============================================================================

interface TestResult {
  test: string;
  status: 'running' | 'pass' | 'fail' | 'skip';
  timestamp: string;
  result?: unknown;
  error?: string;
  duration_ms?: number;
}

function logTest(name: string, status: TestResult['status'], extra?: Partial<TestResult>) {
  const result: TestResult = {
    test: name,
    status,
    timestamp: new Date().toISOString(),
    ...extra
  };
  console.log(JSON.stringify(result));
}

function debug(msg: string) {
  console.error(`[TEST] ${msg}`);
}

async function runTest(name: string, fn: () => Promise<void>) {
  logTest(name, 'running');
  const start = Date.now();
  try {
    await fn();
    logTest(name, 'pass', { duration_ms: Date.now() - start });
  } catch (err) {
    logTest(name, 'fail', { error: String(err), duration_ms: Date.now() - start });
  }
}

function skipTest(name: string, reason: string) {
  logTest(name, 'skip', { error: reason });
}

// =============================================================================
// Tests
// =============================================================================

debug('test-core-prompts.ts starting...');

// -----------------------------------------------------------------------------
// arg() tests
// -----------------------------------------------------------------------------

await runTest('arg-string-choices', async () => {
  const result = await arg('Select a fruit', ['Apple', 'Banana', 'Cherry']);
  if (typeof result !== 'string') {
    throw new Error(`Expected string, got ${typeof result}`);
  }
  debug(`arg result: ${result}`);
});

await runTest('arg-structured-choices', async () => {
  const result = await arg('Select action', [
    { name: 'Run', value: 'run', description: 'Execute script' },
    { name: 'Edit', value: 'edit', description: 'Open editor' },
  ]);
  if (typeof result !== 'string') {
    throw new Error(`Expected string value, got ${typeof result}`);
  }
  debug(`arg structured result: ${result}`);
});

// -----------------------------------------------------------------------------
// div() tests
// -----------------------------------------------------------------------------

await runTest('div-html-content', async () => {
  await div('<h1>Test Content</h1><p>This is a test paragraph.</p>');
  // Success = no error thrown
});

await runTest('div-with-markdown', async () => {
  await div(md(`# Markdown Test
  
  - Item 1
  - Item 2
  
  **Bold** and *italic* text.`));
});

// -----------------------------------------------------------------------------
// editor() tests
// -----------------------------------------------------------------------------

await runTest('editor-empty', async () => {
  const result = await editor();
  if (typeof result !== 'string') {
    throw new Error(`Expected string, got ${typeof result}`);
  }
});

await runTest('editor-with-content', async () => {
  const initial = 'console.log("hello")';
  const result = await editor(initial, 'javascript');
  if (typeof result !== 'string') {
    throw new Error(`Expected string, got ${typeof result}`);
  }
});

// -----------------------------------------------------------------------------
// mini() tests
// -----------------------------------------------------------------------------

await runTest('mini-basic', async () => {
  const result = await mini('Quick input', ['Option A', 'Option B']);
  if (typeof result !== 'string') {
    throw new Error(`Expected string, got ${typeof result}`);
  }
});

// -----------------------------------------------------------------------------
// micro() tests
// -----------------------------------------------------------------------------

await runTest('micro-basic', async () => {
  const result = await micro('Tiny prompt', ['X', 'Y', 'Z']);
  if (typeof result !== 'string') {
    throw new Error(`Expected string, got ${typeof result}`);
  }
});

// -----------------------------------------------------------------------------
// select() tests
// -----------------------------------------------------------------------------

await runTest('select-multi', async () => {
  const result = await select('Select multiple', ['One', 'Two', 'Three']);
  if (!Array.isArray(result)) {
    throw new Error(`Expected array, got ${typeof result}`);
  }
});

debug('test-core-prompts.ts completed!');
