// Auto-generated by scripts/generate-api-tests.ts
// Do not edit manually - regenerate with: bun run scripts/generate-api-tests.ts

import '../../scripts/kit-sdk';

// =============================================================================
// Test Infrastructure
// =============================================================================

interface TestResult {
  test: string;
  status: 'running' | 'pass' | 'fail' | 'skip';
  timestamp: string;
  result?: unknown;
  error?: string;
  duration_ms?: number;
}

function logTest(name: string, status: TestResult['status'], extra?: Partial<TestResult>) {
  const result: TestResult = {
    test: name,
    status,
    timestamp: new Date().toISOString(),
    ...extra
  };
  console.log(JSON.stringify(result));
}

function debug(msg: string) {
  console.error(`[TEST] ${msg}`);
}

async function runTest(name: string, fn: () => Promise<void>) {
  logTest(name, 'running');
  const start = Date.now();
  try {
    await fn();
    logTest(name, 'pass', { duration_ms: Date.now() - start });
  } catch (err) {
    logTest(name, 'fail', { error: String(err), duration_ms: Date.now() - start });
  }
}

function skipTest(name: string, reason: string) {
  logTest(name, 'skip', { error: reason });
}

// =============================================================================
// Tests
// =============================================================================

debug('test-form-inputs.ts starting...');

// -----------------------------------------------------------------------------
// fields() tests
// -----------------------------------------------------------------------------

await runTest('fields-string-array', async () => {
  const [firstName, lastName] = await fields(['First Name', 'Last Name']);
  if (typeof firstName !== 'string' || typeof lastName !== 'string') {
    throw new Error('Expected string values from fields()');
  }
  debug(`fields result: [${firstName}, ${lastName}]`);
});

await runTest('fields-structured', async () => {
  const [email, age] = await fields([
    { name: 'email', label: 'Email', type: 'email', placeholder: 'you@example.com' },
    { name: 'age', label: 'Age', type: 'number', placeholder: '25' },
  ]);
  if (typeof email !== 'string' || typeof age !== 'string') {
    throw new Error('Expected string values from fields()');
  }
});

// -----------------------------------------------------------------------------
// form() tests
// -----------------------------------------------------------------------------

await runTest('form-html', async () => {
  const result = await form(`
    <input name="username" placeholder="Username" />
    <input name="password" type="password" placeholder="Password" />
  `);
  if (typeof result !== 'object') {
    throw new Error(`Expected object, got ${typeof result}`);
  }
});

// -----------------------------------------------------------------------------
// template() tests
// -----------------------------------------------------------------------------

await runTest('template-basic', async () => {
  const result = await template('Hello $1, welcome to $2!');
  if (typeof result !== 'string') {
    throw new Error(`Expected string, got ${typeof result}`);
  }
});

// -----------------------------------------------------------------------------
// env() tests
// -----------------------------------------------------------------------------

await runTest('env-basic', async () => {
  const result = await env('TEST_API_KEY');
  if (typeof result !== 'string') {
    throw new Error(`Expected string, got ${typeof result}`);
  }
});

debug('test-form-inputs.ts completed!');
